### ISSUE TITLE
May have found an issue with reserved words in customLogging

### ISSUE THREAD

**Issue by iancrowther** [pinojs/pino#751]
Howdy folks,

Just came across an issue in an existing code base where ```domain``` is being used as a customLevels key.

```
const defaultConfig = {
  timestamp: getIsoTime,
  useLevelLabels: true,
  redact: {
    paths: REDACT_FIELDS,
    censor: '** REDACTED **',
  },
  customLevels: {
    domain: 31,
    infra: 32,
    request: 33,
    response: 34,
  },
  serializers: {
    err: pino.stdSerializers.err,
    req: pino.stdSerializers.req,
    res: pino.stdSerializers.res,
  },
};
```

This appears to be causing a conflict with the EventEmitter domain.enter function when upgrading some Lambda functions from v8.10.0 to v10.16.3

Could Pino have some reserved words for log level names?

**Comment by iancrowther** [comment]
cc' @leovingi

**Comment by mcollina** [comment]
Hi @iancrowther! I'm not really aware of anything like this. What error are you getting? Can you paste a full script to reproduce?

**Comment by iancrowther** [comment]
Hey @mcollina - hope things are good with you! 

```
{
    "errors": [
        {
            "message": "Context creation failed: domain.enter is not a function",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "TypeError: Context creation failed: domain.enter is not a function",
                        "    at Pino.EventEmitter.emit (domain.js:465:10)",
                        "    at Pino.setLevel (/var/task/node_modules/pino/lib/levels.js:82:8)",
                        "    at pino (/var/task/node_modules/pino/pino.js:119:24)",
                        "    at Object.exports.logger (/var/task/src/logger.js:58:24)",
                        "    at ApolloServer.context (/var/task/src/index.js:37:30)",
                        "    at ApolloServer.<anonymous> (/var/task/node_modules/apollo-server-core/dist/ApolloServer.js:440:38)",
                        "    at Generator.next (<anonymous>)",
                        "    at fulfilled (/var/task/node_modules/apollo-server-core/dist/ApolloServer.js:4:58)",
                        "    at propagateAslWrapper (/var/task/node_modules/async-listener/index.js:504:23)",
                        "    at /var/task/node_modules/async-listener/glue.js:188:31",
                        "    at /var/task/node_modules/async-listener/index.js:541:70",
                        "    at /var/task/node_modules/async-listener/glue.js:188:31"
                    ]
                }
            }
        }
    ]
}
```

if I pull ```domain``` from the above ```defaultConfig``` then all is well

Not too sure what else to give you re: steps to reproduce

**Comment by mcollina** [comment]
I think you have some other issues that are not really pino-related. It can be some interaction between async-listener, Apollo and pino.

I would need some repro code to be able to fix. A PR would even be better.

**Comment by iancrowther** [comment]
This may very well be the case, will put together a repo isolating the scenario and get back to you.

**Comment by iancrowther** [comment]
@mcollina - closing as this is indeed not an issue with Pino.  🎉
