### ISSUE TITLE
REGRESSION: BaseLogger logging methods removed in v9.8.0 - breaks FastifyBaseLogger compatibility

### ISSUE THREAD

**Issue by FrozenPandaz** [pinojs/pino#2253]
## Regression Description

**This is a regression introduced in pino v9.8.0** where the logging methods (`error`, `info`, `warn`, `debug`, etc.) were removed from the `BaseLogger` type definition, causing a breaking change that affects downstream libraries extending `BaseLogger`.

## Reproduction

**Repository:** https://github.com/FrozenPandaz/pino-logger-type-repro

**Steps to reproduce:**
1. Clone the reproduction repo
2. Run `npm install && npm run reproduce`

**TypeScript errors with pino 9.8.0:**
```
Property 'error' does not exist on type 'FastifyBaseLogger'.
Property 'info' does not exist on type 'FastifyBaseLogger'.
```

## Version Comparison (Regression Evidence)

- ✅ **pino@9.7.0**: All logging methods available on BaseLogger *(WORKING)*
- ❌ **pino@9.8.0**: Logging methods missing from BaseLogger *(REGRESSION)*

This worked correctly in v9.7.0 and broke in v9.8.0, making this a clear regression.

## Impact

This **regression** affects **Fastify's FastifyBaseLogger** interface:

```typescript
// From fastify/types/logger.d.ts
export interface FastifyBaseLogger extends pino.BaseLogger {
  child(bindings: Bindings, options?: ChildLoggerOptions): FastifyBaseLogger;
}
```

When projects override pino versions (common in monorepos), Fastify applications using `FastifyBaseLogger` get TypeScript errors because the expected logging methods are no longer part of the `BaseLogger` interface.

## Environment

- **Pino version:** 9.8.0 *(regression from working 9.7.0)*
- **TypeScript version:** 5.0.0+
- **Affected libraries:** Fastify, and potentially others extending BaseLogger

## Expected Behavior

The `BaseLogger` interface should include the standard logging methods (`error`, `info`, `warn`, `debug`, `trace`, `fatal`) as it did in v9.7.0, restoring the previous working behavior and maintaining backward compatibility for libraries that extend this interface.

## Priority

This should be treated as a **high-priority regression** as it breaks existing working code that depends on the BaseLogger interface.

**Comment by mcollina** [comment]
The types are there. Can you upload a reproduction somewhere?

**Comment by devlux** [comment]
> Can you upload a reproduction somewhere?

I guess it's mentioned in the bugreport: https://github.com/FrozenPandaz/pino-logger-type-repro?

**Comment by mcollina** [comment]
I totally missed it, thanks.

**Comment by mcollina** [comment]
I took at look at the example and changing how typescript is invoked fixed it with no code change.

```
diff --git a/package.json b/package.json
index 07a4b38..0d9f8ba 100644
--- a/package.json
+++ b/package.json
@@ -3,16 +3,17 @@
   "version": "1.0.0",
   "description": "Reproduction showing pino version override breaking FastifyBaseLogger",
   "scripts": {
-    "reproduce": "npx tsc --noEmit fastify-override-test.ts"
+    "reproduce": "tsc"
   },
   "dependencies": {
+    "@types/node": "^24.2.1",
     "fastify": "^5.4.0",
     "pino": "9.8.0"
   },
   "devDependencies": {
-    "typescript": "^5.0.0"
+    "typescript": "^5.9.0"
   },
   "overrides": {
     "pino": "9.8.0"
   }
-}
\ No newline at end of file
+}
diff --git a/tsconfig.json b/tsconfig.json
index 3e01ac1..63eb96f 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -3,8 +3,9 @@
     "target": "ES2020",
     "module": "commonjs",
     "strict": true,
+    "noEmit": true,
     "esModuleInterop": true,

```

**Comment by joshkel** [comment]
If I understand correctly, including `"esModuleInterop": true` should fix this. (In the repro, [tsconfig.json is ignored](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#using-tsconfigjson-or-jsconfigjson) because a file is given. Setting `"skipLibCheck": true` is often convenient but here makes the problem worse; it leaves Fastify's use of Pino broken but doesn't tell you what's wrong.)

https://github.com/fastify/fastify/pull/6292 should update Fastify's types so that they work regardless of the `esModuleInterop` setting.

**Comment by rozzilla** [comment]
👀

**Comment by rozzilla** [comment]
You can see an example of this issue [here](https://github.com/platformatic/watt-admin/pull/104/files#diff-5e5e34fb386f9d65556b4fc9b032f3207a07ba1a18616ae880326fde26376a40R48): updating a library (that updates the inner dependency of `pino`) caused a type incompatibility with the `FastifyInstance`.

I can no longer use `FastifyBaseLogger['warn']`, or I will have this typescript issue:
```shell
[10:12:50.165] FATAL (backend/47120): Building service "backend" has throw an exception: Command failed with exit code 1: watt-admin/node_modules/typescript/bin/tsc --project watt-admin/web/backend/tsconfig.json --rootDir watt-admin/web/backend

test/utils/metrics.test.ts:59:42 - error TS2493: Tuple type '[msg: string]' of length '1' has no element at index '1'.

59   assert.ok(warn.mock.calls[0].arguments[1]?.includes('Unable to get runtime metrics'))
                                            ~

test/utils/metrics.test.ts:59:46 - error TS2339: Property 'includes' does not exist on type 'never'.

59   assert.ok(warn.mock.calls[0].arguments[1]?.includes('Unable to get runtime metrics'))
                                                ~~~~~~~~


Found 2 errors in the same file, starting at: test/utils/metrics.test.ts:59
    err: {
      "type": "Error",
      "message": "Command failed with exit code 1: watt-admin/node_modules/typescript/bin/tsc --project watt-admin/web/backend/tsconfig.json --rootDir watt-admin/web/backend\n\ntest/utils/metrics.test.ts:59:42 - error TS2493: Tuple type '[msg: string]' of length '1' has no element at index '1'.\n\n59   assert.ok(warn.mock.calls[0].arguments[1]?.includes('Unable to get runtime metrics'))\n                                            ~\n\ntest/utils/metrics.test.ts:59:46 - error TS2339: Property 'includes' does not exist on type 'never'.\n\n59   assert.ok(warn.mock.calls[0].arguments[1]?.includes('Unable to get runtime metrics'))\n                                                ~~~~~~~~\n\n\nFound 2 errors in the same file, starting at: test/utils/metrics.test.ts:59",
      "stack":
          ExecaError: Command failed with exit code 1: watt-admin/node_modules/typescript/bin/tsc --project watt-admin/web/backend/tsconfig.json --rootDir watt-admin/web/backend
          
          test/utils/metrics.test.ts:59:42 - error TS2493: Tuple type '[msg: string]' of length '1' has no element at index '1'.
          
          59   assert.ok(warn.mock.calls[0].arguments[1]?.includes('Unable to get runtime metrics'))
                                                      ~
          
          test/utils/metrics.test.ts:59:46 - error TS2339: Property 'includes' does not exist on type 'never'.
          
          59   assert.ok(warn.mock.calls[0].arguments[1]?.includes('Unable to get runtime metrics'))
                                                          ~~~~~~~~
          
          
          Found 2 errors in the same file, starting at: test/utils/metrics.test.ts:59
              at getFinalError (file://watt-admin/node_modules/execa/lib/return/final-error.js:6:9)
              at makeError (file://watt-admin/node_modules/execa/lib/return/result.js:108:16)
              at getAsyncResult (file://watt-admin/node_modules/execa/lib/methods/main-async.js:168:4)
              at handlePromise (file://watt-admin/node_modules/execa/lib/methods/main-async.js:151:17)
              at async compile (watt-admin/node_modules/@platformatic/ts-compiler/compile.js:41:3)
              at async ServiceStackable.build (watt-admin/node_modules/@platformatic/service/lib/stackable.js:98:5)
              at async #handleRequest (watt-admin/node_modules/@platformatic/itc/lib/itc.js:287:24)
    }
```

**Comment by mcollina** [comment]
This was fixed in fastify 5.6.0
